    # _config.yml
    title: "گاه‌نوشت‌های یک زریر"
    description: "وبلاگ شخصی"
    author: "زریر"
    baseurl: ""
    url: "https://javanmardx.github.io"

    # تنظیمات
    encoding: UTF-8
    markdown: kramdown
    highlighter: rouge
    permalink: /:year/:month/:day/:title/

    # تنظیمات تاریخ
    timezone: Asia/Tehran

    # تم
    theme: minima

    # پلاگین‌ها
    plugins:
      - jekyll-feed
      - jekyll-seo-tag
      - jekyll-paginate # این خط را اضافه کن

    # پشتیبانی از فارسی
    lang: fa-IR

    # تنظیمات پست‌ها
    defaults:
      - scope:
          path: "_posts"
        values:
          layout: "post"
          permalink: /:year/:month/:day/:title/

    # تنظیمات صفحه‌بندی (این بخش را اضافه کن)
    paginate: 10 # تعداد پست در هر صفحه
    paginate_path: "/page:num/" # ساختار URL برای صفحات بعدی
